import { Counter } from "../types/admin_types"

export const countertypes: Counter[] = [
    {
      counterId: 1,
      counterName:"Counter 1" ,
      userName:"John Doe" ,
      status:"Occupied",
      position: "Accounts",
      email: "johndoeeee@/gmail.com",
      managed: "Payments or Transfer",
    },
    {
      counterId: 2,
      counterName:"Counter 1" ,
      userName:"John Doe" ,
      status:"Unoccupied",
      position: "Accounts",
      email: "johndoeeee@/gmail.com",
      managed: "Customer Service",
    },
    {
      counterId: 3,
      counterName:"Counter 1" ,
      userName:"John Doe" ,
      status:"Unoccupied",
      position: "Accounts",
      email: "johndoeeee@/gmail.com",
      managed: "Accountancy",
    },
    {
      counterId: 4,
      counterName:"Counter 1" ,
      userName:"John Doe" ,
      status:"Occupied",
      position: "Accounts",
      email: "johndoeeee@/gmail.com",
      managed: "Administration",
    },
    {
      counterId: 5,
      counterName:"Counter 1" ,
      userName:"John Doe" ,
      status:"Occupied",
      position: "Accounts",
      email: "johndoeeee@/gmail.com",
      managed: "Appointments",
    },
    
    // {
    //   counterId: 6,
    //   counterName:"Counter 1" ,
    //   userName:"Empty" ,
    //   status: "Empty",
    //   position: "Empty",
    //   email:  "Empty",
    //   managed:  "Empty",
    // },
    // {
    //     counterId: 7,
    //     counterName:"Counter 1" ,
    //     userName:"Empty" ,
    //     status: "Empty",
    //     position: "Empty",
    //     email:  "Empty",
    //     managed:  "Empty",
    //   },
    //   {
    //     counterId: 8,
    //     counterName:"Counter 1" ,
    //     userName:"Empty" ,
    //     status: "Empty",
    //     position: "Empty",
    //     email:  "Empty",
    //     managed:  "Empty",
    //   },
    //   {
    //     counterId: 9,
    //     counterName:"Counter 1" ,
    //     userName:"Empty" ,
    //     status: "Empty",
    //     position: "Empty",
    //     email:  "Empty",
    //     managed:  "Empty",
    //   },
    //   {
    //     counterId: 10,
    //     counterName:"Counter 1" ,
    //     userName:"Empty" ,
    //     status: "Empty",
    //     position: "Empty",
    //     email:  "Empty",
    //     managed:  "Empty",
    //   },
    //   {
    //     counterId: 11,
    //     counterName:"Counter 1" ,
    //     userName:"Empty" ,
    //     status: "Empty",
    //     position: "Empty",
    //     email:  "Empty",
    //     managed:  "Empty",
    //   },
    //   {
    //     counterId: 12,
    //     counterName:"Counter 1" ,
    //     userName:"Empty" ,
    //     status: "Empty",
    //     position: "Empty",
    //     email:  "Empty",
    //     managed:  "Empty",
    //   },
        
  ]

