import { Users } from "../types/admin_types"

export const usertypes: Users[] = [
    {
      userId: 1,
      image:"https://github.com/shadcn.png",
      userName:"John Doe" ,
      status:"Offline",
      role: "Admin",
      position: "Accounts",
      email: "johndoeeee@/gmail.com",
      joined: 5,
      dept: "Accountancy",
    },
    {
      userId: 2,
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUieUDPLZAyoZfDucvczgqA3ZG4kGn5uXKDvekraw8JA&s",
      userName:"Riki Tiu",
      status:"Online",
      role: "Admin",
      position: "hehe",
      email: "johndoeeee@/gmail.com",
      joined: 1,
      dept: "backEnd",
    },
    {
      userId: 3,
      image:"https://github.com/shadcn.png",
      userName:"Gabriel" ,
      status:"Offline",
      role: "Staff",
      position: "tae",
      email: "johndoeeee@/gmail.com",
      joined: 5,
      dept: "front end",
    },
    {
      userId: 4,
      image:"https://github.com/shadcn.png",
      userName:"Raves" ,
      status:"Offline",
      role: "Staff",
      position: "tae",
      email: "johndoeeee@/gmail.com",
      joined: 5,
      dept: "front end",
    },
    {
      userId: 5,
      image:"https://github.com/shadcn.png",
      userName:"Rendell" ,
      status:"Offline",
      role: "Staff",
      position: "tae",
      email: "johndoeeee@/gmail.com",
      joined: 1,
      dept: "front end",
    },
    {
      userId: 6,
      image:"https://github.com/shadcn.png",
      userName:"Mesias" ,
      status:"Online",
      role: "Staff",
      position: "tae",
      email: "johndoeeee@/gmail.com",
      joined: 5,
      dept: "front end",
    },
    {
      userId: 7,
      image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu78mrliqvhdGqRUu2n1cFCgwWT3xEoRAejMahrsydww&s",
      userName:"Julio" ,
      status:"Offline",
      role: "Staff",
      position: "tae",
      email: "johndoeeee@/gmail.com",
      joined: 5,
      dept: "front end",
    },
    {
      userId: 8,
      image:"https://github.com/shadcn.png",
      userName:"dwayne" ,
      status:"Online",
      role: "Staff",
      position: "tae",
      email: "johndoeeee@/gmail.com",
      joined: 5,
      dept: "front end",
    },
  ]