export type QueueTicket = {
    id: number,
    ticket: number,
    customerType: "Regular" | "Senior/PWD/Pregnant",
    counter: "Accounts" | "Loans and Mortgages" | "Registrar" | "Treasury",
    date: string,
    status: "Waiting" | "Finished" | "Cancelled",
}

export const queueTickets: QueueTicket[] = [
  {
    id: 1,
    ticket: 159,
    customerType: "Regular",
    counter: "Accounts",
    date: "2/19/2024",
    status: "Waiting",
  },
  {
    id: 2,
    ticket: 106,
    customerType: "Regular",
    counter: "Treasury",
    date: "6/14/2021",
    status: "Cancelled",
  },
  {
    id: 3,
    ticket: 412,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "8/5/2020",
    status: "Finished",
  },
  {
    id: 4,
    ticket: 206,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "7/27/2020",
    status: "Cancelled",
  },
  {
    id: 5,
    ticket: 461,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "6/25/2021",
    status: "Waiting",
  },
  {
    id: 6,
    ticket: 387,
    customerType: "Regular",
    counter: "Treasury",
    date: "5/9/2024",
    status: "Waiting",
  },
  {
    id: 7,
    ticket: 276,
    customerType: "Regular",
    counter: "Treasury",
    date: "11/27/2020",
    status: "Waiting",
  },
  {
    id: 8,
    ticket: 177,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "1/15/2022",
    status: "Finished",
  },
  {
    id: 9,
    ticket: 487,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "3/29/2024",
    status: "Cancelled",
  },
  {
    id: 10,
    ticket: 340,
    customerType: "Regular",
    counter: "Accounts",
    date: "5/6/2024",
    status: "Waiting",
  },
  {
    id: 11,
    ticket: 244,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "5/20/2024",
    status: "Finished",
  },
  {
    id: 12,
    ticket: 493,
    customerType: "Regular",
    counter: "Accounts",
    date: "11/3/2020",
    status: "Finished",
  },
  {
    id: 13,
    ticket: 490,
    customerType: "Regular",
    counter: "Registrar",
    date: "7/1/2020",
    status: "Finished",
  },
  {
    id: 14,
    ticket: 374,
    customerType: "Regular",
    counter: "Accounts",
    date: "5/22/2021",
    status: "Waiting",
  },
  {
    id: 15,
    ticket: 244,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "3/14/2021",
    status: "Finished",
  },
  {
    id: 16,
    ticket: 462,
    customerType: "Regular",
    counter: "Treasury",
    date: "4/11/2023",
    status: "Waiting",
  },
  {
    id: 17,
    ticket: 170,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "8/12/2023",
    status: "Finished",
  },
  {
    id: 18,
    ticket: 264,
    customerType: "Regular",
    counter: "Accounts",
    date: "9/29/2021",
    status: "Cancelled",
  },
  {
    id: 19,
    ticket: 182,
    customerType: "Regular",
    counter: "Treasury",
    date: "1/19/2024",
    status: "Finished",
  },
  {
    id: 20,
    ticket: 340,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "7/29/2020",
    status: "Finished",
  },
  {
    id: 21,
    ticket: 427,
    customerType: "Regular",
    counter: "Treasury",
    date: "11/13/2021",
    status: "Waiting",
  },
  {
    id: 22,
    ticket: 201,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "7/15/2023",
    status: "Finished",
  },
  {
    id: 23,
    ticket: 265,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "6/20/2022",
    status: "Waiting",
  },
  {
    id: 24,
    ticket: 448,
    customerType: "Regular",
    counter: "Treasury",
    date: "2/11/2021",
    status: "Finished",
  },
  {
    id: 25,
    ticket: 146,
    customerType: "Regular",
    counter: "Registrar",
    date: "12/2/2021",
    status: "Waiting",
  },
  {
    id: 26,
    ticket: 308,
    customerType: "Regular",
    counter: "Treasury",
    date: "8/19/2023",
    status: "Waiting",
  },
  {
    id: 27,
    ticket: 399,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "4/23/2022",
    status: "Waiting",
  },
  {
    id: 28,
    ticket: 486,
    customerType: "Regular",
    counter: "Accounts",
    date: "5/31/2023",
    status: "Finished",
  },
  {
    id: 29,
    ticket: 270,
    customerType: "Regular",
    counter: "Accounts",
    date: "12/29/2023",
    status: "Finished",
  },
  {
    id: 30,
    ticket: 113,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "7/30/2020",
    status: "Finished",
  },
  {
    id: 31,
    ticket: 484,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "12/12/2020",
    status: "Finished",
  },
  {
    id: 32,
    ticket: 132,
    customerType: "Regular",
    counter: "Registrar",
    date: "5/17/2024",
    status: "Waiting",
  },
  {
    id: 33,
    ticket: 449,
    customerType: "Regular",
    counter: "Treasury",
    date: "4/25/2024",
    status: "Finished",
  },
  {
    id: 34,
    ticket: 324,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "9/24/2020",
    status: "Waiting",
  },
  {
    id: 35,
    ticket: 468,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "4/6/2024",
    status: "Cancelled",
  },
  {
    id: 36,
    ticket: 294,
    customerType: "Regular",
    counter: "Treasury",
    date: "4/12/2021",
    status: "Cancelled",
  },
  {
    id: 37,
    ticket: 237,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "4/12/2023",
    status: "Waiting",
  },
  {
    id: 38,
    ticket: 470,
    customerType: "Regular",
    counter: "Treasury",
    date: "9/11/2022",
    status: "Cancelled",
  },
  {
    id: 39,
    ticket: 433,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "7/3/2023",
    status: "Finished",
  },
  {
    id: 40,
    ticket: 342,
    customerType: "Regular",
    counter: "Registrar",
    date: "8/18/2023",
    status: "Cancelled",
  },
  {
    id: 41,
    ticket: 331,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "7/12/2020",
    status: "Waiting",
  },
  {
    id: 42,
    ticket: 373,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "4/8/2023",
    status: "Cancelled",
  },
  {
    id: 43,
    ticket: 372,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "4/22/2023",
    status: "Finished",
  },
  {
    id: 44,
    ticket: 266,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "6/27/2023",
    status: "Cancelled",
  },
  {
    id: 45,
    ticket: 359,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "1/23/2022",
    status: "Finished",
  },
  {
    id: 46,
    ticket: 198,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "4/4/2023",
    status: "Cancelled",
  },
  {
    id: 47,
    ticket: 197,
    customerType: "Regular",
    counter: "Accounts",
    date: "12/27/2022",
    status: "Finished",
  },
  {
    id: 48,
    ticket: 277,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "5/19/2022",
    status: "Cancelled",
  },
  {
    id: 49,
    ticket: 490,
    customerType: "Regular",
    counter: "Accounts",
    date: "6/16/2023",
    status: "Waiting",
  },
  {
    id: 50,
    ticket: 130,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "3/9/2022",
    status: "Cancelled",
  },
  {
    id: 51,
    ticket: 330,
    customerType: "Regular",
    counter: "Treasury",
    date: "1/28/2022",
    status: "Waiting",
  },
  {
    id: 52,
    ticket: 321,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "11/5/2022",
    status: "Cancelled",
  },
  {
    id: 53,
    ticket: 269,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "2/23/2022",
    status: "Cancelled",
  },
  {
    id: 54,
    ticket: 325,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "10/8/2023",
    status: "Finished",
  },
  {
    id: 55,
    ticket: 422,
    customerType: "Regular",
    counter: "Accounts",
    date: "5/26/2022",
    status: "Finished",
  },
  {
    id: 56,
    ticket: 360,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "8/16/2020",
    status: "Finished",
  },
  {
    id: 57,
    ticket: 349,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "5/7/2021",
    status: "Waiting",
  },
  {
    id: 58,
    ticket: 113,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "7/20/2020",
    status: "Finished",
  },
  {
    id: 59,
    ticket: 328,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "10/8/2022",
    status: "Waiting",
  },
  {
    id: 60,
    ticket: 470,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "7/1/2020",
    status: "Finished",
  },
  {
    id: 61,
    ticket: 455,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "5/29/2022",
    status: "Waiting",
  },
  {
    id: 62,
    ticket: 425,
    customerType: "Regular",
    counter: "Accounts",
    date: "12/5/2020",
    status: "Waiting",
  },
  {
    id: 63,
    ticket: 104,
    customerType: "Regular",
    counter: "Treasury",
    date: "2/10/2024",
    status: "Waiting",
  },
  {
    id: 64,
    ticket: 215,
    customerType: "Regular",
    counter: "Registrar",
    date: "6/18/2021",
    status: "Finished",
  },
  {
    id: 65,
    ticket: 402,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "8/26/2021",
    status: "Waiting",
  },
  {
    id: 66,
    ticket: 376,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "1/4/2021",
    status: "Cancelled",
  },
  {
    id: 67,
    ticket: 426,
    customerType: "Regular",
    counter: "Treasury",
    date: "12/16/2023",
    status: "Waiting",
  },
  {
    id: 68,
    ticket: 442,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "9/16/2022",
    status: "Waiting",
  },
  {
    id: 69,
    ticket: 194,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "8/10/2023",
    status: "Finished",
  },
  {
    id: 70,
    ticket: 247,
    customerType: "Regular",
    counter: "Treasury",
    date: "10/11/2021",
    status: "Waiting",
  },
  {
    id: 71,
    ticket: 261,
    customerType: "Regular",
    counter: "Loans and Mortgages",
    date: "5/20/2021",
    status: "Waiting",
  },
  {
    id: 72,
    ticket: 475,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "2/19/2024",
    status: "Waiting",
  },
  {
    id: 73,
    ticket: 345,
    customerType: "Regular",
    counter: "Registrar",
    date: "7/17/2023",
    status: "Finished",
  },
  {
    id: 74,
    ticket: 102,
    customerType: "Regular",
    counter: "Registrar",
    date: "6/2/2023",
    status: "Finished",
  },
  {
    id: 75,
    ticket: 135,
    customerType: "Regular",
    counter: "Treasury",
    date: "9/2/2022",
    status: "Waiting",
  },
  {
    id: 76,
    ticket: 367,
    customerType: "Regular",
    counter: "Accounts",
    date: "10/5/2021",
    status: "Waiting",
  },
  {
    id: 77,
    ticket: 483,
    customerType: "Regular",
    counter: "Treasury",
    date: "7/13/2021",
    status: "Finished",
  },
  {
    id: 78,
    ticket: 457,
    customerType: "Regular",
    counter: "Accounts",
    date: "2/25/2021",
    status: "Cancelled",
  },
  {
    id: 79,
    ticket: 447,
    customerType: "Regular",
    counter: "Registrar",
    date: "6/3/2022",
    status: "Finished",
  },
  {
    id: 80,
    ticket: 488,
    customerType: "Regular",
    counter: "Registrar",
    date: "7/20/2021",
    status: "Finished",
  },
  {
    id: 81,
    ticket: 177,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "8/29/2021",
    status: "Finished",
  },
  {
    id: 82,
    ticket: 356,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "9/13/2023",
    status: "Waiting",
  },
  {
    id: 83,
    ticket: 161,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "1/2/2024",
    status: "Waiting",
  },
  {
    id: 84,
    ticket: 104,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "2/17/2023",
    status: "Finished",
  },
  {
    id: 85,
    ticket: 270,
    customerType: "Regular",
    counter: "Registrar",
    date: "1/2/2024",
    status: "Cancelled",
  },
  {
    id: 86,
    ticket: 259,
    customerType: "Regular",
    counter: "Accounts",
    date: "3/28/2021",
    status: "Cancelled",
  },
  {
    id: 87,
    ticket: 134,
    customerType: "Regular",
    counter: "Treasury",
    date: "12/19/2023",
    status: "Finished",
  },
  {
    id: 88,
    ticket: 438,
    customerType: "Regular",
    counter: "Accounts",
    date: "1/15/2021",
    status: "Waiting",
  },
  {
    id: 89,
    ticket: 374,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "8/9/2021",
    status: "Waiting",
  },
  {
    id: 90,
    ticket: 315,
    customerType: "Senior/PWD/Pregnant",
    counter: "Accounts",
    date: "5/19/2024",
    status: "Finished",
  },
  {
    id: 91,
    ticket: 425,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "12/6/2023",
    status: "Waiting",
  },
  {
    id: 92,
    ticket: 453,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "1/20/2024",
    status: "Finished",
  },
  {
    id: 93,
    ticket: 215,
    customerType: "Regular",
    counter: "Treasury",
    date: "6/24/2020",
    status: "Finished",
  },
  {
    id: 94,
    ticket: 182,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "3/19/2023",
    status: "Cancelled",
  },
  {
    id: 95,
    ticket: 335,
    customerType: "Senior/PWD/Pregnant",
    counter: "Loans and Mortgages",
    date: "5/27/2021",
    status: "Waiting",
  },
  {
    id: 96,
    ticket: 337,
    customerType: "Regular",
    counter: "Registrar",
    date: "9/15/2020",
    status: "Finished",
  },
  {
    id: 97,
    ticket: 382,
    customerType: "Senior/PWD/Pregnant",
    counter: "Treasury",
    date: "5/16/2021",
    status: "Finished",
  },
  {
    id: 98,
    ticket: 437,
    customerType: "Regular",
    counter: "Treasury",
    date: "1/2/2023",
    status: "Finished",
  },
  {
    id: 99,
    ticket: 120,
    customerType: "Senior/PWD/Pregnant",
    counter: "Registrar",
    date: "5/9/2022",
    status: "Waiting",
  },
  {
    id: 100,
    ticket: 384,
    customerType: "Regular",
    counter: "Treasury",
    date: "12/2/2023",
    status: "Cancelled",
  },
];

