/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KioskLayoutRouteImport } from './routes/_kiosk-layout/route'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as KioskLayoutKioskIndexImport } from './routes/_kiosk-layout/kiosk/index'
import { Route as KioskLayoutKioskPagesNowServingRouteImport } from './routes/_kiosk-layout/kiosk/_pages/now-serving/route'

// Create/Update Routes

const KioskLayoutRouteRoute = KioskLayoutRouteImport.update({
  id: '/_kiosk-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const KioskLayoutKioskIndexRoute = KioskLayoutKioskIndexImport.update({
  path: '/kiosk/',
  getParentRoute: () => KioskLayoutRouteRoute,
} as any)

const KioskLayoutKioskPagesNowServingRouteRoute =
  KioskLayoutKioskPagesNowServingRouteImport.update({
    path: '/kiosk/now-serving',
    getParentRoute: () => KioskLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_kiosk-layout': {
      preLoaderRoute: typeof KioskLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
    '/_kiosk-layout/kiosk/': {
      preLoaderRoute: typeof KioskLayoutKioskIndexImport
      parentRoute: typeof KioskLayoutRouteImport
    }
    '/_kiosk-layout/kiosk/_pages/now-serving': {
      preLoaderRoute: typeof KioskLayoutKioskPagesNowServingRouteImport
      parentRoute: typeof KioskLayoutRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  KioskLayoutRouteRoute.addChildren([
    KioskLayoutKioskIndexRoute,
    KioskLayoutKioskPagesNowServingRouteRoute,
  ]),
  AdminIndexRoute,
])

/* prettier-ignore-end */
