/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const KioskRouteLazyImport = createFileRoute('/kiosk')()
const AdminRouteLazyImport = createFileRoute('/admin')()

// Create/Update Routes

const KioskRouteLazyRoute = KioskRouteLazyImport.update({
  path: '/kiosk',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/kiosk/route.lazy').then((d) => d.Route))

const AdminRouteLazyRoute = AdminRouteLazyImport.update({
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/admin/route.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      preLoaderRoute: typeof AdminRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/kiosk': {
      preLoaderRoute: typeof KioskRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AdminRouteLazyRoute,
  KioskRouteLazyRoute,
])

/* prettier-ignore-end */
